name: .NET Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build On Debug
      run: dotnet build --no-restore
    - name: Test On Debug
      run: dotnet test --no-build --verbosity normal
    - name: Build On Release
      run: dotnet build --no-restore --configuration Release
    - name: Test On Release
      run: dotnet test --no-build --verbosity normal -- configuration Release
