name: .NET Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix: 
        configuration: [Debug, Release]

    env:
      CONFIG: ${{ matrix.configuration }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build On ${{ matrix.configuration }}
      run: dotnet build --no-restore --configuration $CONFIG
    - name: Test On ${{ matrix.configuration }}
      run: dotnet test --no-build --verbosity normal --configuration $CONFIG -- Xunit.ParallelizeTestCollections=false MaxParallelThreads=1
