name: .NET Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  setup:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore

  test:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        
    env:
      configuration: ${{ matrix.configuration }}
        
    steps:
    - name: Build
      run: dotnet build --no-restore --configuration ${env:configuration}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${env:configuration}
